<?php  //[STAMP] d3685a80f8f81bf473be4032631f1c0a
namespace XerviceTest\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait XerviceTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
